apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","meta.helm.sh/release-name":"external-dns","meta.helm.sh/release-namespace":"kube-system"},"creationTimestamp":"2025-04-22T11:24:33Z","generation":1,"labels":{"app.kubernetes.io/instance":"external-dns","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"external-dns","app.kubernetes.io/version":"0.13.6","helm.sh/chart":"external-dns-1.13.1"},"name":"external-dns","namespace":"kube-system","resourceVersion":"1171","uid":"24fdb2f4-d765-412e-a7b3-ed055b8ddeb7"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"external-dns","app.kubernetes.io/name":"external-dns"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"external-dns","app.kubernetes.io/name":"external-dns"}},"spec":{"containers":[{"args":["--log-level=debug","--log-format=text","--interval=1m","--source=service","--source=ingress","--policy=sync","--registry=txt","--txt-owner-id=k8s","--domain-filter=natsuki-cloud.dev","--provider=aws"],"image":"registry.k8s.io/external-dns/external-dns:v0.13.6","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":2,"httpGet":{"path":"/healthz","port":"http","scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"external-dns","ports":[{"containerPort":7979,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":6,"httpGet":{"path":"/healthz","port":"http","scheme":"HTTP"},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true,"runAsNonRoot":true,"runAsUser":65534},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":65534,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccount":"external-dns","serviceAccountName":"external-dns","terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2025-04-22T12:26:43Z","lastUpdateTime":"2025-04-22T12:26:43Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2025-04-22T11:24:33Z","lastUpdateTime":"2025-04-22T12:28:22Z","message":"ReplicaSet \"external-dns-5fd788b446\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":3,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
    meta.helm.sh/release-name: external-dns
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2025-04-22T12:29:42Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.13.6
    helm.sh/chart: external-dns-1.13.1
  name: external-dns
  namespace: kube-system
  resourceVersion: "20018"
  uid: df0ad777-ce0f-41cb-895d-bf67f8911c62
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-dns
      app.kubernetes.io/name: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: external-dns
        app.kubernetes.io/name: external-dns
    spec:
      containers:
      - args:
        - --log-level=debug
        - --log-format=text
        - --interval=1m
        - --source=service
        - --source=ingress
        - --policy=sync
        - --registry=txt
        - --txt-owner-id=k8s
        - --domain-filter=natsuki-cloud.dev
        - --provider=aws
        image: registry.k8s.io/external-dns/external-dns:v0.13.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: external-dns
        ports:
        - containerPort: 7979
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: external-dns
      serviceAccountName: external-dns
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-22T12:29:55Z"
    lastUpdateTime: "2025-04-22T12:29:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-22T12:29:42Z"
    lastUpdateTime: "2025-04-22T12:29:55Z"
    message: ReplicaSet "external-dns-6b6996b8ff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
