apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../../app-base

replicas:
- name: todo-frontend
  count: 3  # Production scale
- name: todo-backend
  count: 3  # Production scale  
- name: todo-ai-service
  count: 2  # Production scale

images:
- name: todo-frontend
  newName: 476114111588.dkr.ecr.ap-northeast-1.amazonaws.com/todo-frontend
  newTag: 0.1.80
- name: todo-backend
  newName: 476114111588.dkr.ecr.ap-northeast-1.amazonaws.com/todo-backend
  newTag: 0.1.80
- name: todo-ai-service
  newName: 476114111588.dkr.ecr.ap-northeast-1.amazonaws.com/todo-ai-service
  newTag: 0.1.80

patches:
- target:
    kind: Ingress
    name: todo-app-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: todo-app.natsuki-cloud.dev  # Production domain
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi# Production environment promotion test
