---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-service-monitor
  namespace: todo-app
  labels:
    app: todo-ai-service
    prometheus: devops
spec:
  selector:
    matchLabels:
      app: todo-ai-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s