---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  namespace: todo-app
  annotations:
    cert-manager.io/cluster-issuer: http-01-production
    nginx.ingress.kubernetes.io/hsts: "false"
    nginx.ingress.kubernetes.io/hsts-max-age: "0"
    external-dns.alpha.kubernetes.io/hostname: internal-app.natsuki-cloud.dev
    external-dns.alpha.kubernetes.io/ttl: "300"
    external-dns.alpha.kubernetes.io/owner-id: k8s
    nginx.ingress.kubernetes.io/server-snippet: |
      # Allow ACME challenge paths for Let's Encrypt, otherwise require CloudFront header
      set $block_request 0;
      if ($request_uri !~ ^/\.well-known/acme-challenge/) {
        set $block_request 1;
      }
      if ($http_x_cloudfront_access = "cloudfront-origin-access-2025") {
        set $block_request 0;
      }
      if ($block_request = 1) {
        return 403;
      }
spec:
  ingressClassName: external-nginx
  rules:
    - host: internal-app.natsuki-cloud.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /tasks
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3002
          - path: /callback
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
                  
  tls:
    - hosts:
        - internal-app.natsuki-cloud.dev
      secretName: internal-app-natsuki-cloud-dev