apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-app-natsuki-cloud-dev
  namespace: todo-app
spec:
  secretName: internal-app-natsuki-cloud-dev
  issuerRef:
    name: dns-01-production
    kind: ClusterIssuer
  dnsNames:
  - internal-app.natsuki-cloud.dev