apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
  - namespace-todo-app.yaml
  - frontend-deployment.yaml
  - backend-sa.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - backend-service.yaml
  - frontend-hpa.yaml
  - backend-hpa.yaml
  - horizontal-runner-autoscaler.yaml
  - ingress.yaml
  - cluster-issuer.yaml
  - sealed-repo-secret.yaml
  - sealed-github-app-secret.yaml
  - runner-deployment.yaml