---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: repo-secret
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgCF+pAbZkoxt3fTaX+ezbf40+vufNihuqJI+9aw21TUj6tUWv6xyPR/W6OyTkPXzsirjj0HuHiCBQgo6Rud7+dLGH74V6xLUTAFhUxo3qmsJR2UTDrBRxrmMm5pwmeVwYU0D68CsCMU7jU68JEJUeumnnBPQNAuTnfu2NL3UBYtpGT3a9l5KzpeoYHKW/KSj160SP81uKbVk3YIxQXdxi5DDQ2ZVMNGpGo5ftJ194X5Xl0rNAq+jBu7GAoNt4hNPkTjvpqafz6SjothZJB3LaCx3xbiphjLHwflw1D9o1v90J0XczzE0uxI12W/kCI3/GhZhXa0dleyVwzPMfzp3oYzdg0KXr5CADoaA/blumSEkcDhQvwESulPJ4zzDt6eIaO/v39cduyi+GsIUgqIQ8kVB9xgBoIdwN8Cv9Vf+mOdZGmMSF8JOCLWLj+IM0svTbwgrcAowMlyHWvU+fBP//sPx+4TNXJ+JsxnQEg78k3kk/gH6I8oIx28zntR0C12WhPCm26hcEPbgOucQ259gqBiekH3VnUncD/tGKEq/sWlGFoFhv+8IP+Okmo9hytE0YdFys58+ahdBqlh6NKfeJkSP3uZLHr1IK1vehXPf0xkv8dGK8WyM3eBHmLGNENUfnsg2Vv8PEKlERK0Oq2kCH79F1zhq2ejf6TwEczJNp5ts5PppklIs7YLRP7uvbM8LmBf7mjwJ61LIAEga1wDpP2DK6yO8rRLltxnGiEPjZGlYYepp3/ibaAMyI2Bi7pQHamKoGMay2STxI1mNFk83k+f4XSMXF7HrSxnmCwLv8SKGCryZplE3w6l/XYVl5E4vi/wt4trsi555AapKhzpU7fASh+uLI0WvMBd7FtNhxPxoKJGX56DXNTJfOQDEFiXMaROdN8VVtW755H2Vqt4YTnyRGp+PZxpoXjv6jTpUg7xf0QDfRmJ1AXYnPI/AisLpVwkOIAxMdDEu/P1tRkb4tHorHQAYq12jm+cTuBql3GA/zmixbxdZ86aODHWvvx0vtjiouMdtn95rUsZJ28EuoM+4H6Zpdscx3dAxE6DHkjlQOcFIEibqdhYZF2o37ezrIPmPAZnyn1vKnr86HXNTGALepKtKANlOjm8wSUeKfYR5qf8JTxrBTkSWOjOXh7G+n1l5qusHauLYxJnddcbYueIm0TqeiBxDfKUZSjjWUsN5s2mlaZSn7Hs9smJziwuDR6ASwvaScED3m/q4BZOTg5aLwsIespPAQoJSw==
    url: AgCgya5NuGpQE7DCPR35tjiY7W6xNqjVqCgfDPwFxwnLDgE16g16tg1GE/x2WNtiUO9flIcyOnNkC40scbOs+Zb8Vc15knVcAcUUeTIvExBdjgOVUvs1mOxRPqy2S2rw4T8So0Rktex742zxstt3Vg/m5wOQx4DUiw7urmNYPuAQvms8IRRFQ+jpA+n+Pv3SAcdJ01Z8mBy7bS1tgZlH8O/hQynvNaCMDB0qSmzjAZPNfgtyGw/OFTQC3Mhjpml43XJPphY2frNLz/6fUrO7cGMxdMxQlcyT7Z4yrfbQ8/MJegPTTNwnIA2ahGx0IY5mZz9vMQeTmMMrwoifw43Hlrlu2WCIS7trIEj7Mef05cYrXicXUn6thKHyisnPVV22ObvGBVqR6CGLM7ZBps3PZtMl2Nv2TcUsMq4k+A+vUGU1YbDfltnXoeEnj1QMdiFdSdSvm1GYzDPiiXgGsOEh9oieVWThrS5RBqz4y0BD3lcG9gKODC0CeozRSq8Qu91YymHR1H90Oen3493nvYZHps6/nGXl22MhIaSSm766uiPI0AFtdtpYC/rRplJL5CJYFKFBW2W28UOSOPzVP43VaKWlgIlq5yQqdUKlHG3ONr4v/rkaCEBDSymxDT3+2kEtCEYbmmH62iLy9X7gifBqgJM0cqAnH5lUb0BSnft+vymAv3PSBiq1m93PcrF3AuXnVtvhWCt7EEPqqS+C7tCbT3pFwcofkdJdnnt+BYPR2C4T+eHMWx6Y9fAQVnW2/A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-secret
      namespace: argocd
