apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tsuki-yo/todo-table.git
    path: infra/k8s/environments/production/app
    targetRevision: main  # Production tracks main branch
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true