---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 881490098269.dkr.ecr.ap-northeast-1.amazonaws.com/todo-frontend:~0.1.1,881490098269.dkr.ecr.ap-northeast-1.amazonaws.com/todo-backend:~0.1.1
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/repo-secret
    #argocd-image-updater.argoproj.io/write-back-target: "kustomization:/infra/k8s/environments/staging/app" 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tsuki-yo/todo-table.git
    targetRevision: deploy
    path: infra/k8s/environments/staging/app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
