---
metrics:
  enabled: true

securityContext:
  readOnlyRootFilesystem: false

config:
  registries:
    - name: ECR
      api_url: https://881490098269.dkr.ecr.ap-northeast-1.amazonaws.com
      prefix: 881490098269.dkr.ecr.ap-northeast-1.amazonaws.com
      ping: yes
      default: true
      insecure: false
      credentials: ext:/scripts/ecr-login.sh    
      credsexpire: 12h

authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |
      #!/bin/sh
      HOME=/tmp aws ecr --region "ap-northeast-1" get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d