apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tsuki-yo/todo-table.git
    path: infra/k8s/environments/staging/app
    targetRevision: dev  # Staging tracks dev branch
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true